package com.pengxh.app.weatherplus.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pengxh.app.weatherplus.bean.CityInfoDaoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CITY_INFO_DAO_BEAN".
*/
public class CityInfoDaoBeanDao extends AbstractDao<CityInfoDaoBean, Long> {

    public static final String TABLENAME = "CITY_INFO_DAO_BEAN";

    /**
     * Properties of entity CityInfoDaoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property City = new Property(1, String.class, "city", false, "CITY");
        public final static Property Cityid = new Property(2, String.class, "cityid", false, "CITYID");
        public final static Property Citycode = new Property(3, String.class, "citycode", false, "CITYCODE");
    }


    public CityInfoDaoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CityInfoDaoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CITY_INFO_DAO_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CITY\" TEXT," + // 1: city
                "\"CITYID\" TEXT," + // 2: cityid
                "\"CITYCODE\" TEXT);"); // 3: citycode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CITY_INFO_DAO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CityInfoDaoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String cityid = entity.getCityid();
        if (cityid != null) {
            stmt.bindString(3, cityid);
        }
 
        String citycode = entity.getCitycode();
        if (citycode != null) {
            stmt.bindString(4, citycode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CityInfoDaoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(2, city);
        }
 
        String cityid = entity.getCityid();
        if (cityid != null) {
            stmt.bindString(3, cityid);
        }
 
        String citycode = entity.getCitycode();
        if (citycode != null) {
            stmt.bindString(4, citycode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CityInfoDaoBean readEntity(Cursor cursor, int offset) {
        CityInfoDaoBean entity = new CityInfoDaoBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // city
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cityid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // citycode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CityInfoDaoBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCityid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCitycode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CityInfoDaoBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CityInfoDaoBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CityInfoDaoBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
