package com.pengxh.app.weatherplus.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pengxh.app.weatherplus.bean.CityDaoBean;
import com.pengxh.app.weatherplus.bean.CityInfoDaoBean;
import com.pengxh.app.weatherplus.bean.CityNameDaoBean;

import com.pengxh.app.weatherplus.greendao.CityDaoBeanDao;
import com.pengxh.app.weatherplus.greendao.CityInfoDaoBeanDao;
import com.pengxh.app.weatherplus.greendao.CityNameDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoBeanDaoConfig;
    private final DaoConfig cityInfoDaoBeanDaoConfig;
    private final DaoConfig cityNameDaoBeanDaoConfig;

    private final CityDaoBeanDao cityDaoBeanDao;
    private final CityInfoDaoBeanDao cityInfoDaoBeanDao;
    private final CityNameDaoBeanDao cityNameDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoBeanDaoConfig = daoConfigMap.get(CityDaoBeanDao.class).clone();
        cityDaoBeanDaoConfig.initIdentityScope(type);

        cityInfoDaoBeanDaoConfig = daoConfigMap.get(CityInfoDaoBeanDao.class).clone();
        cityInfoDaoBeanDaoConfig.initIdentityScope(type);

        cityNameDaoBeanDaoConfig = daoConfigMap.get(CityNameDaoBeanDao.class).clone();
        cityNameDaoBeanDaoConfig.initIdentityScope(type);

        cityDaoBeanDao = new CityDaoBeanDao(cityDaoBeanDaoConfig, this);
        cityInfoDaoBeanDao = new CityInfoDaoBeanDao(cityInfoDaoBeanDaoConfig, this);
        cityNameDaoBeanDao = new CityNameDaoBeanDao(cityNameDaoBeanDaoConfig, this);

        registerDao(CityDaoBean.class, cityDaoBeanDao);
        registerDao(CityInfoDaoBean.class, cityInfoDaoBeanDao);
        registerDao(CityNameDaoBean.class, cityNameDaoBeanDao);
    }
    
    public void clear() {
        cityDaoBeanDaoConfig.clearIdentityScope();
        cityInfoDaoBeanDaoConfig.clearIdentityScope();
        cityNameDaoBeanDaoConfig.clearIdentityScope();
    }

    public CityDaoBeanDao getCityDaoBeanDao() {
        return cityDaoBeanDao;
    }

    public CityInfoDaoBeanDao getCityInfoDaoBeanDao() {
        return cityInfoDaoBeanDao;
    }

    public CityNameDaoBeanDao getCityNameDaoBeanDao() {
        return cityNameDaoBeanDao;
    }

}
